"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { FileText, Download, BookOpen } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"

interface ReportGeneratorProps {
  projectName: string
  projectDescription: string
  messageCount: number
  userCount: number
  onClose: () => void
}

export function ReportGenerator({
  projectName,
  projectDescription,
  messageCount,
  userCount,
  onClose,
}: ReportGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [reportType, setReportType] = useState<"pdf" | "srs" | null>(null)

  const generatePDFReport = () => {
    setIsGenerating(true)
    setTimeout(() => {
      const element = document.createElement("div")
      element.innerHTML = `
        <html>
          <head>
            <title>${projectName} - Report</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
              h1 { color: #0066cc; border-bottom: 3px solid #0066cc; padding-bottom: 10px; }
              h2 { color: #0099ff; margin-top: 30px; }
              .header { margin-bottom: 40px; }
              .section { margin-bottom: 30px; page-break-inside: avoid; }
              .stats { display: flex; gap: 20px; margin: 20px 0; }
              .stat-box { border: 1px solid #ddd; padding: 15px; border-radius: 8px; flex: 1; }
              .stat-value { font-size: 24px; font-weight: bold; color: #0066cc; }
              .stat-label { color: #666; font-size: 14px; }
              table { width: 100%; border-collapse: collapse; margin: 15px 0; }
              th { background-color: #0066cc; color: white; padding: 10px; text-align: left; }
              td { padding: 10px; border-bottom: 1px solid #ddd; }
              .footer { margin-top: 50px; border-top: 1px solid #ddd; padding-top: 20px; text-align: center; color: #666; font-size: 12px; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>${projectName}</h1>
              <p><strong>Report Generated:</strong> ${new Date().toLocaleDateString()}</p>
              <p><strong>Description:</strong> ${projectDescription}</p>
            </div>

            <div class="section">
              <h2>Project Overview</h2>
              <div class="stats">
                <div class="stat-box">
                  <div class="stat-label">Total Messages</div>
                  <div class="stat-value">${messageCount.toLocaleString()}</div>
                </div>
                <div class="stat-box">
                  <div class="stat-label">Active Users</div>
                  <div class="stat-value">${userCount.toLocaleString()}</div>
                </div>
                <div class="stat-box">
                  <div class="stat-label">Avg Messages per User</div>
                  <div class="stat-value">${(messageCount / Math.max(userCount, 1)).toFixed(2)}</div>
                </div>
              </div>
            </div>

            <div class="section">
              <h2>Project Details</h2>
              <table>
                <tr>
                  <th>Metric</th>
                  <th>Value</th>
                </tr>
                <tr>
                  <td>Project Name</td>
                  <td>${projectName}</td>
                </tr>
                <tr>
                  <td>Total Messages Processed</td>
                  <td>${messageCount.toLocaleString()}</td>
                </tr>
                <tr>
                  <td>Registered Users</td>
                  <td>${userCount}</td>
                </tr>
                <tr>
                  <td>Report Generated</td>
                  <td>${new Date().toLocaleDateString()}</td>
                </tr>
                <tr>
                  <td>Report Type</td>
                  <td>Comprehensive PDF Report</td>
                </tr>
              </table>
            </div>

            <div class="section">
              <h2>Key Insights</h2>
              <ul>
                <li><strong>User Engagement:</strong> Average ${(messageCount / Math.max(userCount, 1)).toFixed(0)} messages per user</li>
                <li><strong>Platform Performance:</strong> System is handling ${messageCount} total interactions</li>
                <li><strong>User Base Growth:</strong> ${userCount} active users currently using the platform</li>
              </ul>
            </div>

            <div class="footer">
              <p>This report is generated by ReqNexa AI Chatbot Platform</p>
              <p>For more information, visit your dashboard</p>
            </div>
          </body>
        </html>
      `

      const blob = new Blob([element.innerHTML], { type: "text/html" })
      const url = URL.createObjectURL(blob)
      const link = document.createElement("a")
      link.href = url
      link.download = `${projectName}-report-${new Date().getTime()}.html`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)

      setIsGenerating(false)
      setReportType(null)
    }, 1500)
  }

  const generateSRSTemplate = () => {
    setIsGenerating(true)
    setTimeout(() => {
      const srsContent = `
IEEE SOFTWARE REQUIREMENTS SPECIFICATION (SRS)
Project: ${projectName}
Generated: ${new Date().toLocaleDateString()}

================================================================================
1. INTRODUCTION
================================================================================

1.1 Purpose
This Software Requirements Specification (SRS) document describes the requirements for the ${projectName} chatbot system. This document is intended for both the development team and stakeholders.

1.2 Scope
This specification covers all functional and non-functional requirements for the AI chatbot platform including user interaction, message processing, and analytics capabilities.

1.3 Project Overview
${projectDescription}

1.4 Document Overview
This SRS is organized as follows:
- Section 1: Introduction
- Section 2: Overall Description
- Section 3: External Interface Requirements
- Section 4: System Features
- Section 5: Non-Functional Requirements
- Section 6: Quality Attributes

================================================================================
2. OVERALL DESCRIPTION
================================================================================

2.1 System Overview
The system is an AI-powered chatbot platform designed to:
- Process user queries in natural language
- Generate intelligent responses using AI
- Maintain conversation history
- Track user engagement metrics
- Generate detailed reports

2.2 System Capabilities
- Real-time message processing
- Multi-user support and management
- Analytics and reporting
- Project-based organization
- User authentication and security

2.3 User Classes
- Regular Users: Access the chatbot and chat history
- Administrators: Manage projects and users
- Analysts: Generate reports and view analytics

2.4 Operating Environment
- Web-based application
- Compatible with modern browsers
- Cloud-hosted infrastructure
- API-based architecture

2.5 Design and Implementation Constraints
- Responsive design for mobile and desktop
- RESTful API architecture
- Database-driven data persistence
- Real-time communication capabilities

================================================================================
3. EXTERNAL INTERFACE REQUIREMENTS
================================================================================

3.1 User Interfaces
- Dashboard with project overview
- Chat interface for user interactions
- Settings and configuration pages
- Report generation interface

3.2 Hardware Interfaces
- Standard web browsers (Chrome, Firefox, Safari, Edge)
- Desktop and mobile devices
- Network connectivity required

3.3 Software Interfaces
- Backend API services
- Database management system
- Authentication services
- Report generation services

================================================================================
4. SYSTEM FEATURES
================================================================================

4.1 Project Management
Requirement ID: REQ-4.1.1
The system shall allow users to create, edit, and delete chatbot projects.

Requirement ID: REQ-4.1.2
The system shall display project statistics including message count and user count.

4.2 Chat Functionality
Requirement ID: REQ-4.2.1
The system shall accept user messages and generate AI responses.

Requirement ID: REQ-4.2.2
The system shall maintain conversation history.

4.3 Report Generation
Requirement ID: REQ-4.3.1
The system shall generate PDF reports with project analytics.

Requirement ID: REQ-4.3.2
The system shall generate IEEE SRS templates for documentation.

Requirement ID: REQ-4.3.3
The system shall allow report download and export.

4.4 User Authentication
Requirement ID: REQ-4.4.1
The system shall support user sign-in and sign-up.

Requirement ID: REQ-4.4.2
The system shall maintain user sessions securely.

================================================================================
5. NON-FUNCTIONAL REQUIREMENTS
================================================================================

5.1 Performance Requirements
- System shall process messages within 2 seconds
- Dashboard shall load within 3 seconds
- Report generation shall complete within 5 seconds

5.2 Security Requirements
- All data shall be encrypted in transit (HTTPS)
- User passwords shall be hashed and salted
- Access control shall be enforced per user

5.3 Reliability Requirements
- System uptime shall be 99.9%
- Data backup shall occur daily
- Error recovery shall be automatic

5.4 Scalability Requirements
- System shall support 10,000+ concurrent users
- Database shall scale horizontally
- API load balancing shall be implemented

5.5 Usability Requirements
- Interface shall be intuitive and user-friendly
- Mobile-responsive design
- Accessible to users with disabilities (WCAG 2.1)

================================================================================
6. QUALITY ATTRIBUTES
================================================================================

6.1 Maintainability
Code shall follow industry standards and best practices.

6.2 Portability
Application shall run on major web browsers and operating systems.

6.3 Compatibility
System shall maintain API compatibility across versions.

================================================================================
END OF SRS DOCUMENT
================================================================================

Current Project Statistics:
- Total Messages: ${messageCount.toLocaleString()}
- Active Users: ${userCount}
- Average Messages per User: ${(messageCount / Math.max(userCount, 1)).toFixed(2)}

Generated by ReqNexa AI Chatbot Platform
`

      const element = document.createElement("a")
      const file = new Blob([srsContent], { type: "text/plain" })
      element.href = URL.createObjectURL(file)
      element.download = `${projectName}-SRS-${new Date().getTime()}.txt`
      document.body.appendChild(element)
      element.click()
      document.body.removeChild(element)

      setIsGenerating(false)
      setReportType(null)
    }, 1500)
  }

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          className="border-blue-500/50 text-blue-400 hover:bg-blue-500/10 bg-transparent"
        >
          <FileText className="h-4 w-4" />
        </Button>
      </DialogTrigger>
      <DialogContent className="border-border max-w-md">
        <DialogHeader>
          <DialogTitle className="text-foreground">Generate Report</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <p className="text-sm text-muted-foreground">Select report type for {projectName}</p>

          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-3">
            {/* PDF Report Option */}
            <Card
              onClick={() => {
                setReportType("pdf")
                generatePDFReport()
              }}
              className={`p-4 cursor-pointer transition-all border-border ${
                reportType === "pdf" ? "bg-blue-500/20 border-blue-500" : "hover:border-blue-500/50"
              }`}
            >
              <div className="flex items-center gap-3">
                <Download className="h-5 w-5 text-blue-400" />
                <div className="flex-1">
                  <h4 className="font-semibold text-foreground">PDF Report</h4>
                  <p className="text-xs text-muted-foreground">Analytics and project statistics</p>
                </div>
              </div>
            </Card>

            {/* SRS Template Option */}
            <Card
              onClick={() => {
                setReportType("srs")
                generateSRSTemplate()
              }}
              className={`p-4 cursor-pointer transition-all border-border ${
                reportType === "srs" ? "bg-purple-500/20 border-purple-500" : "hover:border-purple-500/50"
              }`}
            >
              <div className="flex items-center gap-3">
                <BookOpen className="h-5 w-5 text-purple-400" />
                <div className="flex-1">
                  <h4 className="font-semibold text-foreground">IEEE SRS Template</h4>
                  <p className="text-xs text-muted-foreground">Software Requirements Specification</p>
                </div>
              </div>
            </Card>
          </motion.div>

          {isGenerating && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex items-center justify-center gap-2 text-sm text-muted-foreground"
            >
              <div className="h-4 w-4 rounded-full border-2 border-blue-500 border-t-transparent animate-spin" />
              Generating report...
            </motion.div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}
